### ISSUE TITLE
Setup github pages documentation

### ISSUE THREAD

**Issue by davecash75** [HealthBioscienceIDEAS/demon-imaging-harmonisation#7]
Hi Haroon-
Could you please setup the github pages documentation framework for this project just like you did for MEDICSS?
Thanks
Dave

**Comment by HChughtai** [comment]
Hey Dave, sorry I missed when you initially sent this. Confirming that I've now seen it and it's in my todo list.

**Comment by HChughtai** [comment]
@davecash75 Initial gh-pages setup done in the same manner as the MedICSS repo. You can view the website here: https://healthbioscienceideas.github.io/demon-imaging-harmonisation/ 

Details about formatting and structure are in the theme documentation: https://pmarsceill.github.io/just-the-docs/

**Comment by davecash75** [comment]
This is perfect. Thank you!
